name-template: 'Release v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
version-template: '$MAJOR.$MINOR'
prerelease: true
categories:
  - title: '🚀 Features'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧰 Meta'
    labels:
      - 'configuration'
      - 'ci'
      - 'documentation'
  - title: '🏭 Libraries update'
    label: 'dependencies'
exclude-labels:
  - 'skip-changelog'
  - 'security'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes
  $CHANGES
replacers:
  - search: '/^(feat):\s*(.*)/g'
    replace: '$2'
  - search: 'feat'
    replace: 'feature'
autolabeler:
  - label: 'configuration'
    files:
      - '.*\\.(config|editorconfig|properties|sql)+$'
    title:
      - '/^(style|refactor|perf|test|chore)(\([\w-]*\))*:\s*.*/i'
  - label: 'security'
    title:
      - '/^(build\(security\)):\s*.*/i'
  - label: 'ci'
    files:
      - '.*(workflows|github).*\.yml$'
    title:
      - '/^(build|ci)(\([\w-]*\))*:\s*.*/i'
  - label: 'bug'
    title:
      - '/^(fix|revert)(\([\w-]*\))*:\s*.*/i'
  - label: 'enhancement'
    title:
      - '/^(feat)(\([\w-]*\))*:\s*.+/i'

